### ISSUE TITLE
Doesn't work with sync protocol in Anki 2.0.27 and greater

### ISSUE THREAD

**Issue by jdoe0** [dsnopek/anki-sync-server#16]
SYNC_URL has been renamed to SYNC_BASE, and the "/sync/" part of the URL is no longer needed, so I think the README should be updated.

**Comment by SenorFusion** [comment]
Hi @dsnopek and @tomzx 

Background, Please see:  https://github.com/ankidroid/Anki-Android/pull/680

In short: 
1. In that discussion, the AnkiDroid team says they are open to accepting pull requests to add a custom Sync URL. (Which AnkiServer asks for in the Readme)

2. @tomzx has submitted a PR at AnkiDroid to do exactly that that has been open for nearly a year.

2. AnkiDroid team won't accept unless there is a version of Anki Sync Server that works with the latest Anki sync protocol.

3. They reference this bug here (16) as proof that Anki-Sync-Server  does NOT work with the current Anki sync protocol.

4. Can we either A) Get this issue fixed B) If it is fixed, someone go to the AnkiDroid thread listed above and tell them so, so they will accept the PR?

**Comment by dsnopek** [comment]
Unfortunately, this still isn't fixed - this issue is still accurate. I haven't had time to devote to AnkiServer because I haven't been working on the project I created it for in quite a while. :-( But PRs are welcome! I''d happily review and commit if someone manages to get the code updated!
